### ISSUE TITLE
Crash in X11 session

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#4]
```
thread 'main' panicked at src/displays.rs:178:74:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x555ffc5e05d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcd708d85b5efed87
   1:     0x555ffc6198d0 - core::fmt::write::hf495c2d26b931328
   2:     0x555ffc5eb5ff - std::io::Write::write_fmt::hac9f74e1a11b4e18
   3:     0x555ffc5e0384 - std::sys_common::backtrace::print::h8138bee0467dea67
   4:     0x555ffc5e10e4 - std::panicking::default_hook::{{closure}}::hf54f0424a9132beb
   5:     0x555ffc5e0df2 - std::panicking::default_hook::h8b9ffbbb82c07751
   6:     0x555ffc5e1608 - std::panicking::rust_panic_with_hook::h0d09c48ad479065c
   7:     0x555ffc5e14ae - std::panicking::begin_panic_handler::{{closure}}::hd0c997cc1624515e
   8:     0x555ffc5e0816 - std::sys_common::backtrace::__rust_end_short_backtrace::h0f38651de3b42fc2
   9:     0x555ffc5e1214 - rust_begin_unwind
  10:     0x555ffc179cc5 - core::panicking::panic_fmt::hacdc5bc0eef2ec30
  11:     0x555ffc179d9d - core::panicking::panic::h3b90346b22d78140
  12:     0x555ffc17a2b6 - core::option::unwrap_failed::ha71681ffbfba1aec
  13:     0x555ffc22391e - core::option::Option<T>::unwrap::h989b3648d9008d62
                               at /tmp/rust-20240410-9701-dq93us/rustc-1.77.2-src/library/core/src/option.rs:931:21
  14:     0x555ffc22391e - crabfetch::displays::parse_xrandr::h9d52b4d31ffc1114
                               at /home/user/CrabFetch/src/displays.rs:178:54
  15:     0x555ffc222902 - crabfetch::displays::get_displays::h8c3b64c18fd69dcd
                               at /home/user/CrabFetch/src/displays.rs:99:42
  16:     0x555ffc20afa3 - crabfetch::main::hec6b64fec4882da0
                               at /home/user/CrabFetch/src/main.rs:194:25
  17:     0x555ffc215d4b - core::ops::function::FnOnce::call_once::h316d57fb7f18326c
                               at /tmp/rust-20240410-9701-dq93us/rustc-1.77.2-src/library/core/src/ops/function.rs:250:5
  18:     0x555ffc17b6ae - std::sys_common::backtrace::__rust_begin_short_backtrace::hd8d34a36c0d24b13
                               at /tmp/rust-20240410-9701-dq93us/rustc-1.77.2-src/library/std/src/sys_common/backtrace.rs:155:18
  19:     0x555ffc193241 - std::rt::lang_start::{{closure}}::h87c7a2b8afd154d8
                               at /tmp/rust-20240410-9701-dq93us/rustc-1.77.2-src/library/std/src/rt.rs:166:18
  20:     0x555ffc5e1114 - std::panicking::try::h96782f09fe81b230
  21:     0x555ffc5fd9db - std::rt::lang_start_internal::hdb182bcd0e96d070
  22:     0x555ffc19321a - std::rt::lang_start::he17b0733e72c4d56
                               at /tmp/rust-20240410-9701-dq93us/rustc-1.77.2-src/library/std/src/rt.rs:165:17
  23:     0x555ffc210dce - main
  24:     0x7f12461461b7 - __libc_start_call_main
  25:     0x7f124614626c - __libc_start_main_alias_2
  26:     0x555ffc17a351 - _start
  27:                0x0 - <unknown>
```

xrandr output

```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 10112 x 5400
VGA-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.00*+  48.00  
   1680x1050     59.95  
   1280x1024     60.02  
   1440x900      59.89  
   1366x768      59.79  
   1280x800      59.81  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
```

This program was trying to parse `VGA-0 disconnected (normal left inverted right x axis y axis)` ( because this line contains String `connected` ).

**Comment by CarterLi** [comment]
Note

```
hyperfine "~/fastfetch/build/fastfetch -c none -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:uptime:break:colors' --pipe false" "xrandr"
Benchmark 1: ~/fastfetch/build/fastfetch -c none -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:uptime:break:colors' --pipe false
  Time (mean ± σ):      26.5 ms ±   1.2 ms    [User: 9.5 ms, System: 16.4 ms]
  Range (min … max):    24.1 ms …  30.0 ms    96 runs
 
Benchmark 2: xrandr
  Time (mean ± σ):      29.0 ms ±   1.0 ms    [User: 1.9 ms, System: 2.0 ms]
  Range (min … max):    27.7 ms …  34.6 ms    102 runs
 
Summary
  ~/fastfetch/build/fastfetch -c none -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:uptime:break:colors' --pipe false ran
    1.10 ± 0.06 times faster than xrandr
```

`xrandr` is slower than the whole fastfetch program. I don't think a program uses that can be faster than fastfetch

**Comment by LivacoNew** [comment]
At work with only a Wayland desktop to play with rn, will get to this once I'm home.
For what it's worth, xrandr is <2ms for me but again that's me in Wayland right now lol.

**Comment by CarterLi** [comment]
Whatever. With these bugs / crashes, the code quality is yet to be improved. I don't think it's worth trying tbh.

**Comment by CarterLi** [comment]
As the author of fastfetch, I was here to find how crabfetch can be faster than fastfetch and is there any that fastfetch can refer to. But I was disappointed.

**Comment by LivacoNew** [comment]
Would still prefer to keep this open so I can keep track of it and look into it. Even if CrabFetch is held together with duct tape and dreams, I do want to keep working on it when I can.
